export const REGISTER_INTERNAL_SYMBOL = Symbol( "REGISTER_INTERNAL" );
export const UNREGISTER_INTERNAL_SYMBOL = Symbol( "UNREGISTER_INTERNAL" );
export const GET_INTERNAL_SYMBOL = Symbol( "GET_INTERNAL_SYMBOL" );
export const GET_INTERNAL_MATCH_SYMBOL = Symbol( "GET_INTERNAL_MATCH_SYMBOL" );
export const LINK_COMPONENTS = Symbol( "LINK_COMPONENTS" );
export const SET_TO_CONTEXT = Symbol( "SET_TO_CONTEXT" );
